### ISSUE TITLE
Reduce [dependencies.ncollide] to just the crates we use

### ISSUE THREAD

**Issue by bfops** [bfops/playform#106]
`ncollide` recently underwent a refactoring into multiple crates. We should depend on only the ones we use. Build times will be better.

**Comment by cgaebel** [comment]
won't this only improve first-build time, as opposed to incremental build time?

**Comment by bfops** [comment]
Yeah that sounds right. But man dat first build time =P.

**Comment by bfops** [comment]
Although actually first build time has gotten better anyway because parallel.

**Comment by cgaebel** [comment]
Yeah I'd just yolo it and depend on ncollide.

**Comment by bfops** [comment]
meh mkay sgtm. My ulterior motive was "I don't want to update all of ncollide just to build playform" but that's not a real reason =P.
