### ISSUE TITLE
Could not compile `serialize`

### ISSUE THREAD

**Issue by oroid** [bfops/playform#129]
Precondition:
OSX 10.9.5, rust 1.0.0
git repo: master

log while client compiled:
   Compiling serialize v0.0.0 (file:///Volumes/TM/prj/rustGames/playform/playform/client)
/Volumes/TM/prj/rustGames/playform/playform/common/serialize/lib.rs:7:1: 7:25 error: unstable feature
/Volumes/TM/prj/rustGames/playform/playform/common/serialize/lib.rs:7 #![feature(collections)]
                                                                      ^~~~~~~~~~~~~~~~~~~~~~~~
note: this feature may not be used in the stable release channel
/Volumes/TM/prj/rustGames/playform/playform/common/serialize/lib.rs:8:1: 8:21 error: unstable feature
/Volumes/TM/prj/rustGames/playform/playform/common/serialize/lib.rs:8 #![feature(convert)]
                                                                      ^~~~~~~~~~~~~~~~~~~~
note: this feature may not be used in the stable release channel
/Volumes/TM/prj/rustGames/playform/playform/common/serialize/lib.rs:9:1: 9:18 error: unstable feature
/Volumes/TM/prj/rustGames/playform/playform/common/serialize/lib.rs:9 #![feature(core)]
                                                                      ^~~~~~~~~~~~~~~~~
note: this feature may not be used in the stable release channel
error: aborting due to 3 previous errors
Build failed, waiting for other jobs to finish...
Could not compile `serialize`.

The same problem is for server and common.

**Comment by bfops** [comment]
Oops, thanks for pointing that out. I should clarify in the README that this uses the nightly release channel. It seems to build fine there.
