### ISSUE TITLE
ttf panic when starting client

### ISSUE THREAD

**Issue by acerix** [bfops/playform#174]
I can't figure out this error when I try to launch the client:

    thread '<main>' panicked at 'assertion failed: !p.is_null()', src/playform-master/client/lib/src/ttf.rs:97

Am I missing a font? I have sdl2_ttf installed.

Also, both client and server are running with over 100% CPU usage at this point: http://imgur.com/FIxFDR8

Let me know how I can provide more info.  Thanks!

**Comment by bfops** [comment]
Oops, I should fix that error message. It means no font was found. Are you running from the root directory or from the `client/bin` directory? It looks for the fonts in a `fonts` folder in the current directory.

**Comment by acerix** [comment]
I have the client binary installed as /usr/bin/playform, and run it from my home directory with the command: "playform".

I just installed [ttf-ubuntu-font-family](https://www.archlinux.org/packages/community/any/ttf-ubuntu-font-family/) and [ttf-opensans](https://aur.archlinux.org/packages/ttf-opensans/), but it didn't help.  Is there another font package I need?

**Comment by bfops** [comment]
The text is removed in master.

**Comment by bfops** [comment]
Ah I haven't paid any attention to how `cargo install` works. I've just been using `cargo build` and `cargo run`. I think it should work now though!

**Comment by acerix** [comment]
Awesome, it works now! Thanks!
