### ISSUE TITLE
Client doesn't build, "use of deprecated item" errors in client/lib/src/block_position.rs

### ISSUE THREAD

**Issue by acerix** [bfops/playform#178]
https://travis-ci.org/bfops/playform/builds/106366468#L1315

`/home/travis/build/bfops/playform/client/lib/src/block_position.rs:18:7: 18:49 error: use of deprecated item: support moved to std::hash, #[deny(deprecated)] on by default
/home/travis/build/bfops/playform/client/lib/src/block_position.rs:18   use std::collections::hash_state::DefaultState;
                                                                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/travis/build/bfops/playform/client/lib/src/block_position.rs:20:58: 20:81 error: use of deprecated item: support moved to std::hash, #[deny(deprecated)] on by default
/home/travis/build/bfops/playform/client/lib/src/block_position.rs:20   pub type T<V> = std::collections::HashMap<super::T, V, DefaultState<FnvHasher>>;
                                                                                                                               ^~~~~~~~~~~~~~~~~~~~~~~
/home/travis/build/bfops/playform/client/lib/src/block_position.rs:23:5: 23:47 error: use of deprecated item: renamed to with_hasher, #[deny(deprecated)] on by default
/home/travis/build/bfops/playform/client/lib/src/block_position.rs:23     std::collections::HashMap::with_hash_state(Default::default())
                                                                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/travis/build/bfops/playform/client/lib/src/block_position.rs:30:7: 30:49 error: use of deprecated item: support moved to std::hash, #[deny(deprecated)] on by default
/home/travis/build/bfops/playform/client/lib/src/block_position.rs:30   use std::collections::hash_state::DefaultState;
                                                                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/travis/build/bfops/playform/client/lib/src/block_position.rs:32:52: 32:75 error: use of deprecated item: support moved to std::hash, #[deny(deprecated)] on by default
/home/travis/build/bfops/playform/client/lib/src/block_position.rs:32   pub type T = std::collections::HashSet<super::T, DefaultState<FnvHasher>>;
                                                                                                                         ^~~~~~~~~~~~~~~~~~~~~~~
/home/travis/build/bfops/playform/client/lib/src/block_position.rs:36:5: 36:47 error: use of deprecated item: renamed to with_hasher, #[deny(deprecated)] on by default
/home/travis/build/bfops/playform/client/lib/src/block_position.rs:36     std::collections::HashSet::with_hash_state(Default::default())
                                                                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/travis/build/bfops/playform/client/lib/src/block_position.rs:48:9: 48:51 error: use of deprecated item: support moved to std::hash, #[deny(deprecated)] on by default
/home/travis/build/bfops/playform/client/lib/src/block_position.rs:48     use std::collections::hash_state::DefaultState;
                                                                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/travis/build/bfops/playform/client/lib/src/block_position.rs:50:54: 50:77 error: use of deprecated item: support moved to std::hash, #[deny(deprecated)] on by default
/home/travis/build/bfops/playform/client/lib/src/block_position.rs:50     pub type T = std::collections::HashSet<super::T, DefaultState<FnvHasher>>;
                                                                                                                           ^~~~~~~~~~~~~~~~~~~~~~~
/home/travis/build/bfops/playform/client/lib/src/block_position.rs:53:7: 53:49 error: use of deprecated item: renamed to with_hasher, #[deny(deprecated)] on by default
/home/travis/build/bfops/playform/client/lib/src/block_position.rs:53       std::collections::HashSet::with_hash_state(Default::default())
                                                                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/travis/build/bfops/playform/client/lib/src/block_position.rs:60:9: 60:51 error: use of deprecated item: support moved to std::hash, #[deny(deprecated)] on by default
/home/travis/build/bfops/playform/client/lib/src/block_position.rs:60     use std::collections::hash_state::DefaultState;
                                                                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/travis/build/bfops/playform/client/lib/src/block_position.rs:62:60: 62:83 error: use of deprecated item: support moved to std::hash, #[deny(deprecated)] on by default
/home/travis/build/bfops/playform/client/lib/src/block_position.rs:62     pub type T<V> = std::collections::HashMap<super::T, V, DefaultState<FnvHasher>>;
                                                                                                                                 ^~~~~~~~~~~~~~~~~~~~~~~
/home/travis/build/bfops/playform/client/lib/src/block_position.rs:65:7: 65:49 error: use of deprecated item: renamed to with_hasher, #[deny(deprecated)] on by default
/home/travis/build/bfops/playform/client/lib/src/block_position.rs:65       std::collections::HashMap::with_hash_state(Default::default())
                                                                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
error: aborting due to 12 previous errors
Could not compile `client-lib`.
`

**Comment by acerix** [comment]
Wow, that was fast! Fixed by:

https://github.com/bfops/playform/commit/ee8f4af8c8a783f80e8a701852ab943b049e17f0

Thanks!

**Comment by bfops** [comment]
Awesome, thanks for the report :)
