### ISSUE TITLE
Compile errors without lockfile

### ISSUE THREAD

**Issue by dns2utf8** [bfops/playform#186]
The screenshots look amazing :+1: 
But I can not compile it because at least `cgmath`, `Aabb3` and `lru-cache` changed their api.

I was able to get a little bit furter after setting 
`lru-cache = "^0.0.7"`
in `server/lib/terrain/Cargo.toml` but not far enough.

**Comment by bfops** [comment]
Thanks for the report! I'll try to update to the latest rustc + packages tonight or in the next couple of days.

**Comment by bfops** [comment]
I think this should be fixed now. Let me know if it's still broken!
