### ISSUE TITLE
Does not compile nightly-x86_64-unknown-linux-gnu (default) rustc 1.19.0-nightly (75b056812 2017-05-15)

### ISSUE THREAD

**Issue by Unmoving** [bfops/playform#190]
`cargo build
    Updating registry `https://github.com/rust-lang/crates.io-index`
    Updating git repository `https://github.com/bfops/stopwatch-rs`
    Updating git repository `https://github.com/bfops/rust-voxel-data`
    Updating git repository `https://github.com/bfops/rust-isosurface-extraction`
    Updating git repository `https://github.com/bfops/yaglw`
 Downloading thread-scoped v1.0.1
 Downloading env_logger v0.4.2
 Downloading hound v3.1.0
 Downloading gl v0.5.2
 Downloading sdl2 v0.22.0
 Downloading portaudio v0.7.0
 Downloading bincode v0.8.0
 Downloading image v0.13.0
 Downloading sdl2-sys v0.22.0
 Downloading gl_generator v0.4.2
 Downloading xml-rs v0.2.2
 Downloading bitflags v0.6.0
 Downloading serde v1.0.5
 Downloading png v0.7.0
 Downloading inflate v0.2.0
 Downloading deflate v0.7.11
 Downloading noise v0.1.5
 Downloading lru-cache v0.1.1
 Downloading linked-hash-map v0.4.2
 Downloading aho-corasick v0.6.3
 Downloading thread-id v3.1.0
   Compiling pkg-config v0.3.9
   Compiling khronos_api v1.0.0
   Compiling byteorder v0.5.3
   Compiling bitflags v0.6.0
   Compiling adler32 v1.0.0
   Compiling void v1.0.2
   Compiling hound v3.1.0
   Compiling num-traits v0.1.37
   Compiling siphasher v0.2.2
   Compiling lazy_static v0.2.8
   Compiling phf_shared v0.7.21
   Compiling portaudio v0.7.0
   Compiling sdl2-sys v0.22.0
   Compiling byteorder v1.0.0
   Compiling enum_primitive v0.1.1
   Compiling num-integer v0.1.34
   Compiling bitflags v0.7.0
   Compiling unreachable v0.1.1
   Compiling phf v0.7.21
   Compiling gcc v0.3.46
   Compiling raw-cpuid v2.0.2
   Compiling num-iter v0.1.33
   Compiling approx v0.1.1
   Compiling linked-hash-map v0.4.2
   Compiling deflate v0.7.11
   Compiling libc v0.2.22
   Compiling serde v1.0.5
warning: redundant linker flag specified for library `SDL2`

   Compiling time v0.1.37
   Compiling cmake v0.1.23
   Compiling thread-id v3.1.0
   Compiling rustc-serialize v0.3.24
   Compiling log v0.3.7
   Compiling nanomsg-sys v0.6.2
   Compiling inflate v0.2.0
warning: redundant linker flag specified for library `nanomsg`

   Compiling lru-cache v0.1.1
   Compiling rand v0.3.15
   Compiling phf_generator v0.7.21
   Compiling cgmath v0.14.1
   Compiling num-complex v0.1.37
   Compiling bincode v0.8.0
   Compiling num-bigint v0.1.37
   Compiling csv v0.14.7
   Compiling png v0.7.0
   Compiling nanomsg v0.6.2
   Compiling cgmath v0.12.0
   Compiling num-rational v0.1.36
   Compiling bitflags v0.3.3
   Compiling xml-rs v0.2.2
   Compiling num v0.1.37
   Compiling serde v0.6.15
   Compiling collision v0.10.0
warning: redundant linker flag specified for library `portaudio`

   Compiling image v0.13.0
   Compiling sdl2 v0.22.0
   Compiling serde_json v0.6.1
   Compiling voxel-data v0.0.0 (https://github.com/bfops/rust-voxel-data#29c12592)
   Compiling gl_generator v0.4.2
   Compiling isosurface-extraction v0.0.0 (https://github.com/bfops/rust-isosurface-extraction#44679ae1)
   Compiling utf8-ranges v1.0.0
   Compiling noise v0.1.5
   Compiling phf_codegen v0.7.21
   Compiling regex-syntax v0.4.0
   Compiling x86 v0.8.1
   Compiling thread-scoped v1.0.1
   Compiling gl v0.5.2
   Compiling memchr v1.0.1
   Compiling aho-corasick v0.6.3
   Compiling thread_local v0.3.3
   Compiling fnv v1.0.5
   Compiling regex v0.2.1
   Compiling yaglw v0.0.0 (https://github.com/bfops/yaglw#a4939e3f)
   Compiling env_logger v0.4.2
   Compiling stopwatch v0.0.0 (https://github.com/bfops/stopwatch-rs#ed6fe158)
   Compiling playform-common v0.0.0 (file:///home/seredmo/projects/playform/common)
error[E0277]: the trait bound `collision::Aabb3<f32>: rustc_serialize::Encodable` is not satisfied
  --> common/protocol.rs:82:24
   |
82 | #[derive(Debug, Clone, RustcEncodable, RustcDecodable)]
   |                        ^^^^^^^^^^^^^^ the trait `rustc_serialize::Encodable` is not implemented for `collision::Aabb3<f32>`
   |
   = note: required by `rustc_serialize::Encodable::encode`

error[E0277]: the trait bound `collision::Aabb3<f32>: rustc_serialize::Decodable` is not ssfied
  --> common/protocol.rs:82:40
   |
82 | #[derive(Debug, Clone, RustcEncodable, RustcDecodable)]
   |                                        ^^^^^^^^^^^^^^ the trait `rustc_serialize::Decble` is not implemented for `collision::Aabb3<f32>`
   |
   = note: required by `rustc_serialize::Decodable::decode`

error: aborting due to 2 previous errors

error: Could not compile `playform-common`.

`

**Comment by bfops** [comment]
Thanks for the report! Looks like `rustc_serialize` is pretty deprecated at this point.

Started a fix in the `rustup` branch

**Comment by bfops** [comment]
Well, one pull request to collision-rs later, it seems to work again!
